
// ===================================================================================
// CONFIGURATION COMMENTS (Translations for Config.h files)
// ===================================================================================

const CONFIG_COMMENTS = {
    hu: {
        // Controller
        "PINMAP": "OFF, Válaszd ki: MiniPCB, MiniPCB2, MaxPCB2, MaxESP3, CNC3, STM32Blue, MaxSTM3, FYSETC_S6_2, stb.",
        "SERIAL_A_BAUD_DEFAULT": "9600, n. Ahol n=9600,19200,57600,115200 (gyakori baud ráták).",
        "SERIAL_B_BAUD_DEFAULT": "9600, n. Baud ráta. Lásd (src/pinmaps/) a port kiosztásokhoz.",
        "SERIAL_B_ESP_FLASHING": "OFF, ON ESP8266 WiFi firmware feltöltése SERIAL_B-n keresztül :ESPFLASH# paranccsal.",
        "SERIAL_C_BAUD_DEFAULT": "OFF, n. Baud ráta.",
        "SERIAL_RADIO": "OFF, Használj BLUETOOTH, WIFI_ACCESS_POINT vagy WIFI_STATION (csak ESP32).",
        "STATUS_LED": "OFF, Folyamatos világítás ha nincs hiba, villog hibakóddal ha van.",
        "RETICLE_LED_DEFAULT": "OFF, n. Ahol n=0..255 (0..100%) bekapcsolja és beállítja az alapértelmezett fényerőt.",
        "RETICLE_LED_MEMORY": "OFF, ON Megjegyzi a szálkereszt fényerőt újraindítás után.",
        "RETICLE_LED_INVERT": "OFF, ON Invertálja a vezérlést (ha 0V a max fényerő).",
        "WEATHER": "OFF, BME280 (I2C 0x77), BME280_0x76, BMP280 hőmérséklethez, nyomáshoz.",
        "STEP_WAVE_FORM": "SQUARE, PULSE Lépés jel hullámforma gyorsabb rátákhoz. SQUARE a legjobb jelintegritáshoz.",
        "NV_DRIVER": "NV_DEF, Az alapértelmezett nem-felejtő memória használata a beállítások tárolására.",
        "DISPLAY_WEATHER": "Weboldal, időjárás megjelenítése",
        "DISPLAY_INTERNAL_TEMPERATURE": "Weboldal, belső MCU hőmérséklet megjelenítése",

        // Mount / Axis
        "MOUNT_TYPE": "GEM, GEM (Német Ekvatoriális), FORK (Villa), vagy ALTAZM (Dobson stb).",
        "MOUNT_COORDS": "TOPOCENTRIC, Refrakció alkalmazása a koordinátákra.",
        "MOUNT_COORDS_MEMORY": "OFF, ON Megjegyzi a hozzávetőleges koordinátákat kikapcsoláskor (FRAM szükséges).",
        "MOUNT_ENABLE_IN_STANDBY": "OFF, ON Bekapcsolva tartja a motorokat készenléti módban.",
        "TIME_LOCATION_SOURCE": "DS3231, OFF, DS3231 (I2C), GPS, vagy NTP forrás.",
        "TIME_LOCATION_PPS_SENSE": "OFF, HIGH PPS (másodpercenkénti impulzus) érzékelése.",
        "STATUS_MOUNT_LED": "OFF, ON Villog a mozgás sebességével arányosan vagy folyamatos slew közben.",
        "STATUS_BUZZER": "2000, OFF, ON, n. Ahol n=100..6000 (Hz frekvencia).",
        "STATUS_BUZZER_DEFAULT": "OFF, ON bekapcsolt hangjelzéssel indul.",
        "STATUS_BUZZER_MEMORY": "ON, OFF, ON megjegyzi a hang beállítást.",
        "ST4_INTERFACE": "OFF, ON engedélyezi az interfészt. <= 1X vezetés.",
        "ST4_HAND_CONTROL": "ON, OFF kézivezérlő támogatás bekapcsolása.",
        "ST4_HAND_CONTROL_FOCUSER": "ON, OFF fókuszáló vezérlés ST4-en keresztül.",
        "GUIDE_TIME_LIMIT": "20, 10, n. Időkorlát n=0..120 másodperc. 0 a kikapcsoláshoz.",
        "GUIDE_DISABLE_BACKLASH": "OFF, Kikapcsolja a holtjáték kompenzációt vezetés közben.",
        "LIMIT_SENSE": "LOW, OFF, HIGH vagy LOW állapot a végálláskapcsolón megállítja a mozgást.",
        "LIMIT_STRICT": "OFF, kikapcsolja a limiteket amíg nincs unpark/sync.",
        "PARK_SENSE": "OFF, HIGH vagy LOW állapot jelzi, hogy a mechanika parkoló állásban van.",
        "PARK_SIGNAL": "OFF, Parkolás indítása külső jelre.",
        "PARK_STATUS": "OFF, Jelzi ha sikeresen parkolt.",
        "PARK_STRICT": "OFF, Csak akkor enged unpark-ot, ha sikeresen parkolt.",
        "PEC_STEPS_PER_WORM_ROTATION": "12800, 0, n. Lépés per csiga fordulat (0 kikapcsolja, egyébként 720 mp buffer).",
        "PEC_SENSE": "OFF, HIGH. PEC jel felfutó él érzékelése.",
        "PEC_BUFFER_SIZE_LIMIT": "720, PEC buffer mérete másodpercben.",
        "TRACK_BACKLASH_RATE": "20, n. Ahol n=2..50 (x sziderikus ráta) a holtjáték kompenzáció alatt.",
        "TRACK_AUTOSTART": "OFF, ON Indításkor a követés automatikusan bekapcsol.",
        "TRACK_COMPENSATION_DEFAULT": "OFF, Refrakció vagy pointing modell kompenzáció alapértelmezés.",
        "TRACK_COMPENSATION_MEMORY": "OFF, ON Megjegyzi a kompenzációs beállításokat.",
        "SLEW_RATE_BASE_DESIRED": "1.0, n. Kívánt sebesség fok/mp-ben. Futásidőben állítható 1/2 és 2x között.",
        "SLEW_RATE_MEMORY": "ON, OFF, ON Megjegyzi a sebességet újraindítás után.",
        "SLEW_ACCELERATION_DIST": "5.0, n (fok). Gyorsítási/lassítási távolság.",
        "SLEW_RAPID_STOP_DIST": "2.0, n (fok). Megállási távolság vészhelyzetben.",
        "GOTO_FEATURE": "ON, OFF a GoTo funkciók letiltásához.",
        "GOTO_OFFSET": "0.25, Eltolás fokban a goto célirányú megközelítéshez, 0.0 kikapcsolja.",
        "GOTO_OFFSET_ALIGN": "OFF, ON kihagyja a végső fázist betanításkor.",
        "MFLIP_SKIP_HOME": "OFF, ON közvetlenül a célra megy home érintése nélkül flipkor.",
        "MFLIP_AUTOMATIC_DEFAULT": "OFF, ON automatikus flip engedélyezése induláskor.",
        "MFLIP_AUTOMATIC_MEMORY": "OFF, ON megjegyzi az automatikus flip beállítást.",
        "MFLIP_PAUSE_HOME_DEFAULT": "OFF, ON megáll home pozícióban flip közben.",
        "PIER_SIDE_SYNC_CHANGE_SIDES": "OFF, ON engedélyezi az oldalváltást sync parancsnál.",
        "PIER_SIDE_PREFERRED_DEFAULT": "BEST, BEST Marad a jelenlegi oldalon ha lehet. EAST vagy WEST vált ha lehet.",
        "PIER_SIDE_PREFERRED_MEMORY": "OFF, ON megjegyzi a preferált oldalt.",
        "ALIGN_AUTO_HOME": "OFF, ON használja a home kapcsolókat a home pozíció megtalálásához igazítás előtt.",
        "ALIGN_MODEL_MEMORY": "OFF, ON visszaállítja a mentett pointing modellt induláskor.",
        "ALIGN_MAX_STARS": "AUTO, Csillagok száma (1-9).",

        // Axis Specific (General patterns)
        "AXIS1_STEPS_PER_DEGREE": "12800, n. Lépés per fok: n = (motor_lépés * mikrolépés * áttétel)/360.0",
        "AXIS1_DRIVER_MODEL": "OFF, Motorvezérlő típusa (pl. TMC2209).",
        "AXIS1_DRIVER_MICROSTEPS": "OFF, n. Mikrolépés mód követés közben.",
        "AXIS1_DRIVER_MICROSTEPS_GOTO": "OFF, n. Mikrolépés mód gyorsmozgás (goto) közben.",
        "AXIS1_DRIVER_IHOLD": "OFF, n (mA). Áram állás közben.",
        "AXIS1_DRIVER_IRUN": "OFF, n, (mA.) Áram követés közben.",
        "AXIS1_DRIVER_IGOTO": "OFF, n (mA). Áram slewing közben.",
        "AXIS1_DRIVER_REVERSE": "OFF, ON Megfordítja a mozgás irányát.",
        "AXIS1_DRIVER_STATUS": "OFF, ON, HIGH, LOW. Driver állapot lekérdezése.",
        "AXIS1_DRIVER_DECAY": "OFF, Decay mód követésnél (STEALTHCHOP).",
        "AXIS1_DRIVER_DECAY_GOTO": "OFF, Decay mód slewingnál (SPREADCYCLE).",
        "AXIS1_POWER_DOWN": "OFF, ON Kikapcsolja a motort ha nem mozog.",
        "AXIS1_SENSE_HOME": "OFF, HIGH vagy LOW engedélyezi a home kapcsolót.",
        "AXIS1_LIMIT_MIN": "-180, n. Minimum 'Óraszög' vagy Azimut.",
        "AXIS1_LIMIT_MAX": "180, n. Maximum 'Óraszög' vagy Azimut.",
        
        "AXIS2_STEPS_PER_DEGREE": "12800, n. Lépés per fok.",
        "AXIS2_DRIVER_MODEL": "OFF, Motorvezérlő típusa.",
        "AXIS2_DRIVER_MICROSTEPS": "OFF, n. Mikrolépés mód követés közben.",
        "AXIS2_DRIVER_MICROSTEPS_GOTO": "OFF, n. Mikrolépés mód gyorsmozgás közben.",
        "AXIS2_DRIVER_IHOLD": "OFF, n (mA). Áram állás közben.",
        "AXIS2_DRIVER_IRUN": "OFF, n (mA). Áram követés közben.",
        "AXIS2_DRIVER_REVERSE": "OFF, ON Megfordítja a mozgás irányát.",
        "AXIS2_LIMIT_MIN": "-90, n. Minimum Deklináció.",
        "AXIS2_LIMIT_MAX": "90, n. Maximum Deklináció.",

        // Focuser / Rotator
        "AXIS3_SLEW_RATE_BASE_DESIRED": "1.0, n. Kívánt sebesség fok/mp-ben.",
        "AXIS3_STEPS_PER_DEGREE": "64.0, n. Lépés per fok rotátornál.",
        "AXIS3_DRIVER_MODEL": "OFF, TMC2130, stb.",
        "AXIS3_LIMIT_MIN": "0, n. Minimum szög.",
        "AXIS3_LIMIT_MAX": "360, n. Maximum szög.",
        
        "AXIS4_SLEW_RATE_BASE_DESIRED": "1000, n, Ahol n=200..5000 (um/s).",
        "AXIS4_SLEW_RATE_MINIMUM": "50, n. Minimum sebesség.",
        "AXIS4_STEPS_PER_MICRON": "0.5, n. Lépés per mikrométer.",
        "AXIS4_DRIVER_MODEL": "TMC2209, OFF.",
        "FOCUSER_TEMPERATURE": "OFF, THERMISTOR vagy n (ds18b20 s/n).",

        "AXIS5_DRIVER_MODEL": "TMC2209, OFF.",
        "AXIS5_STEPS_PER_MICRON": "0.5, n. Lépés per mikrométer.",

        // Features
        "FEATURE1_PURPOSE": "OFF, SWITCH, ANALOG_OUT, DEW_HEATER, stb.",
        "FEATURE1_NAME": "\"FE..\", A vezérelt funkció neve.",
        "FEATURE1_TEMP": "OFF, THERMISTOR vagy n. Hőmérséklet forrás.",
        "FEATURE1_PIN": "OFF, AUX, n. Pin szám.",
        "FEATURE1_VALUE_DEFAULT": "OFF, ON, n. Alapértelmezett érték.",
        "FEATURE1_VALUE_MEMORY": "OFF, ON megjegyzi az állapotot.",
        "FEATURE1_ON_STATE": "HIGH, LOW invertáláshoz.",
        
        "FEATURE2_PURPOSE": "OFF, SWITCH, stb.",
        "FEATURE2_NAME": "\"FE..\"",
        "FEATURE2_PIN": "OFF, AUX, n.",
        
        "THERMISTOR1_TNOM": "Névleges hőmérséklet (Celsius)",
        "THERMISTOR1_RNOM": "Névleges ellenállás (Ohm)",
        "THERMISTOR1_BETA": "Beta együttható",
        "THERMISTOR1_RSERIES": "Soros ellenállás (Ohm)"
    },
    en: {
        // Angol fallback (alapvetően az eredeti file tartalmazza, de a rendszer megköveteli a kulcsokat)
    }
};
